import type {
  InstructorCardSummary,
  InstructorListItem,
  SettlementItemRow,
} from "@/features/jeongsan-builder/types";

export const MOCK_INSTRUCTOR_SUMMARY: InstructorCardSummary = {
  name: "김명훈T",
  subjects: "고등 물리 · 과학한성물리계",
  itemCount: 11,
  gross: 44_990_880,
  deduct: -1_861_782,
  settle: 43_129_098,
  wth: -1_484_699,
  taxable: 44_130_000,
  net: 41_644_399,
  reviewCount: 3,
};

export const MOCK_SETTLEMENT_ROWS: SettlementItemRow[] = [
  {
    code: "R1",
    kind: "revenue",
    name: "과학한성물리A 수업료",
    detail: "과학한성물리A (본) · 24명 · 10h · 순매출 ₩19,984,800",
    sub: "VAT 합산 ₩1,200,000 · 13명 온라인",
    base: {
      type: "dropdown",
      options: [{ id: "g", name: "매출 (VAT포함)" }],
      value: "g",
      computed: "₩ 19,984,800",
    },
    op: { options: [{ id: "r", name: "비율" }], value: "r" },
    aux: "0.6",
    tax: true,
    formula: "19,984,800 × 0.6",
    result: 11_990_880,
    needsReview: false,
  },
  {
    code: "R2",
    kind: "revenue",
    name: "과학한성물리B 수업료",
    detail: "과학한성물리B (본) · 10명 · 12h · 순매출 ₩15,000,000",
    sub: "VAT 합산 ₩500,000",
    base: {
      type: "dropdown",
      options: [{ id: "n", name: "순매출 (VAT제외)" }],
      value: "n",
      computed: "₩ 15,000,000",
    },
    op: { options: [{ id: "r", name: "비율" }], value: "r" },
    aux: "0.6",
    tax: true,
    formula: "15,000,000 × 0.6",
    result: 9_000_000,
    needsReview: false,
  },
  {
    code: "R3",
    kind: "revenue",
    name: "물리특강 시습제",
    detail: "과학한성특강 (본) · 15명 · 12h · 순매출 ₩7,150,000",
    sub: null,
    base: {
      type: "dropdown",
      options: [{ id: "s", name: "시수" }],
      value: "s",
      computed: "12",
    },
    op: { options: [{ id: "u", name: "단가제" }], value: "u" },
    aux: "45000",
    tax: true,
    formula: "12 × 45,000",
    result: 540_000,
    needsReview: false,
  },
  {
    code: "R4",
    kind: "revenue",
    name: "겨울 특강반",
    detail: "과학특강 겨울과정 (본) · 22명 · 20h · 순매출 ₩11,000,000",
    sub: "VAT 합산 ₩500,000",
    base: {
      type: "dropdown",
      options: [{ id: "n", name: "순매출 (VAT제외)" }],
      value: "n",
      computed: "₩ 11,000,000",
    },
    op: { options: [{ id: "r", name: "비율" }], value: "r" },
    aux: "0.58",
    tax: true,
    formula: "11,000,000 × 0.58",
    result: 6_380_000,
    needsReview: false,
  },
  {
    code: "R5",
    kind: "revenue",
    name: "모의고사 대비",
    detail: "보강과정 대비반 (본) · 28명 · 8h · 순매출 ₩5,600,000",
    sub: null,
    base: {
      type: "dropdown",
      options: [{ id: "n", name: "순매출 (VAT제외)" }],
      value: "n",
      computed: "₩ 5,600,000",
    },
    op: { options: [{ id: "r", name: "비율" }], value: "r" },
    aux: "0.55",
    tax: true,
    formula: "5,600,000 × 0.55",
    result: 3_080_000,
    needsReview: false,
  },
  {
    code: "",
    kind: "pay",
    name: "물리과 부장 수당",
    detail: "수기 입력",
    base: { type: "input", value: "500000" },
    op: { options: [{ id: "f", name: "고정" }], value: "f" },
    aux: "",
    tax: true,
    formula: "500,000",
    result: 500_000,
    needsReview: false,
  },
  {
    code: "",
    kind: "pay",
    name: "진단고사 운영",
    detail: "수기 입력",
    base: { type: "input", value: "1000000" },
    op: { options: [{ id: "f", name: "고정" }], value: "f" },
    aux: "",
    tax: true,
    formula: "1,000,000",
    result: 1_000_000,
    needsReview: false,
  },
  {
    code: "",
    kind: "pay",
    name: "우수 강사 격려금",
    detail: "",
    base: { type: "input", value: "12500000" },
    op: { options: [{ id: "f", name: "고정" }], value: "f" },
    aux: "",
    tax: true,
    formula: "12,500,000",
    result: 12_500_000,
    needsReview: true,
  },
];

export const MOCK_INSTRUCTORS: InstructorListItem[] = [
  { name: "김명훈T", subject: "고등 물리", amount: "₩42.7M", dot: "yellow", active: true },
  { name: "정수현T", subject: "고등 화학", amount: "₩36.9M", dot: "green" },
  { name: "박지훈T", subject: "고등 수학", amount: "₩50.4M", dot: "green" },
  { name: "이민영T", subject: "고등 영어", amount: "₩28.6M", dot: "green" },
  { name: "조현우T", subject: "중등 수학", amount: "₩18.1M", dot: "green" },
  { name: "강민석T", subject: "특강", amount: "₩6.6M", dot: "yellow" },
  { name: "류지현T", subject: "조교", amount: "₩5.0M", dot: "green" },
  { name: "최서연T", subject: "강사", amount: "₩21.4M", dot: "green" },
  { name: "민지호T", subject: "강사", amount: "₩30.8M", dot: "green" },
  { name: "송하늘T", subject: "강사", amount: "₩26.6M", dot: "green" },
  { name: "황재현T", subject: "강사", amount: "₩14.1M", dot: "yellow" },
  { name: "임수민T", subject: "강사", amount: "₩18.3M", dot: "green" },
];
